<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>md2pdf</AssemblyName>
    <RootNamespace>Md2Pdf.Cli</RootNamespace>
    <PublishAot>true</PublishAot>
    <IsAotCompatible>true</IsAotCompatible>
    <StripSymbols>true</StripSymbols>
    <JsonSerializerIsReflectionEnabledByDefault>false</JsonSerializerIsReflectionEnabledByDefault>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Md2Pdf.Core/Md2Pdf.Core.csproj" />
  </ItemGroup>
</Project>
