<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsAotCompatible>true</IsAotCompatible>
    <RootNamespace>Md2Pdf.Core</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Markdig" Version="1.3.2" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="browser-manifest.json"
                      LogicalName="Md2Pdf.Core.browser-manifest.json" />
  </ItemGroup>
</Project>
